services:
  backend:
    build: tragent_backend
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "python3 manage.py migrate --noinput && python3 manage.py runserver 0.0.0.0:8080"
    ports:
      - "8080:8080"
    env_file:
      - .env
  postgres:
    image: postgres:latest
    healthcheck :
      test: ["CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval : 5s
      timeout : 3s
      retries : 5
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - .env
  tg-bot:
    build: telegram_bot
    command: python3 bot.py
    depends_on:
      - backend
    env_file:
      - .env
