# Generated by Django 5.0.3 on 2024-03-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_city_remove_user_country_triplocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
